name: Compile CI

on:
  push:
    branches: ["master", "*"]
  pull_request:
    branches: ["master", "*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Wasmtime & Run tests
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          cat /home/runner/.bashrc
          env
          echo "step 2"
          bash -c "env"
          echo "step 3"
          source /home/runner/.bashrc
          echo "step 4"
          env
          echo "step 5"
          bash -c "wasmtime"
