name: Compile CI

on:
  push:
    branches: ["master", "*"]
  pull_request:
    branches: ["master", "*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Wasmtime & Run tests
        run: |
          curl https://wasmtime.dev/install.sh -sSf | bash
          cat /home/runner/.bashrc
          env
          bash -c "env"
          bash -c "which wasmtime"
          source /home/runner/.bashrc
          env
          wasmtime
