name: Compile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install solidity & wasm tools
      run: |
        sudo add-apt-repository ppa:ethereum/ethereum
        sudo apt-get update
        sudo apt-get install -y wabt solc

    - name: Add wasi target
      run: rustup target add wasm32-wasi
      
    - name: Add unknown target
      run: rustup target add wasm32-unknown-unknown
      
    - name: Install dependecies
      run:  cargo fetch
      
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
      
    - name: Build
      run: make

    # - name: Run unit tests
    #   run: make check

    # - name: Install dependencies for lints
    #   run: |
    #     rustup component add rustfmt --toolchain nightly-2022-09-07-x86_64-unknown-linux-gnu
    #     rustup component add clippy --toolchain nightly-2022-09-07-x86_64-unknown-linux-gnu

    # - name: Lints
    #   run: |
    #     cargo fmt --check
    #     cargo clippy --workspace -- -D warnings

    # - name: Install Wasmtime & Run tests
    #   run: |
    #     curl https://wasmtime.dev/install.sh -sSf | bash
    #     export WASMTIME_HOME="$HOME/.wasmtime"
    #     export PATH="$WASMTIME_HOME/bin:$PATH"SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar

    #     bash -c "python3 tools/tests.py"
        
    - name: Install pandas
      run: pip3 install pandas

    - name: Run benchmark
      run: python3 tools/bench.py


    - name: Setup Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Switch to gh-pages branch
      run: |
        git checkout gh-pages

    - name: Copy csv files
      run: |
        mkdir -p csvs
        cp -r tools/benchmark/csvs/* csvs/

    - name: Commit changes
      run: |
        git add csvs/
        git commit -m "Update csv files"
          
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
          branch: gh-pages
          folder: tools/benchmark/pages
          clean: false
