name: Compile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "*" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependecies
      run: cargo build || true
      
    - name: Build
      run: make

    - name: Run unit tests
      run: make check

    - name: Run tests
      run: python3 tools/tests.py

